### ISSUE TITLE
Update readme and documentation

### ISSUE THREAD

**Issue by cbdm** [cbdm/footcal#6]
Explain how to use the service for new users. Could be something similar to what I had done in onefootball-ics: https://github.com/cbdm/onefootball-ics/blob/main/templates/help.html

**Comment by minh-hahaha** [comment]
Hello, I'd like to help with this. What source of data are you planning to use for the calendar now?

**Comment by minh-hahaha** [comment]
I added a pull request. Lmk if I should add anything. Thanks

**Comment by cbdm** [comment]
Just merged that, thanks!

I'll do a quick run on the search function tonight, so hopefully have something that works a little better if you're interested in documenting how to use that, or if you want to contribute with code should be easier after the search is done too.

**Comment by minh-hahaha** [comment]
Sounds good!

**Comment by cbdm** [comment]
Search and caching should be working -- I finished those last night. I also added a help page explaining how to use everything. That's probably it for what I'm doing soon-ish, as those are the things I felt were needed asap and I have to finish other things :)
